### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by elyase** [vuejs/vue-webpack-meteor-example#12]
Has anybody got hot reload working? I installed `webpack-dev-server` and I am running:

```bash
webpack-dev-server --inline --hot
```

but it is not hot reloading, in fact it is not reloading at all. With `webpack --watch` full reload works ok.

**Comment by yyx990803** [comment]
This setup is simply triggerig Meteor reload by writing to disk, so... unfortunately no hot reloading available :(

**Comment by elyase** [comment]
Would this be too difficult to achieve? Actually hot reload is what attracted me to vue.js. The only thing that occurs to me is to iterate on the frontend outside of meteor where hot reload is available and then try to integrate with Meteor data sources at a later stage.

**Comment by yyx990803** [comment]
It should be possible by replicating webpack-dev-server's client side code in the page served by Meteor, although I don't have time to look into that as of now.
