### ISSUE TITLE
奇怪的问题。Meteor的bug？还是Vue的bug？

### ISSUE THREAD

**Issue by zhongqf** [vuejs/vue-webpack-meteor-example#2]
有个很奇怪的问题。
用这个example，如果用两个浏览器进程分别打开，比如一个Chrome，一个Safari，在一个浏览器里，更新了某个document的内容，更新后的数据不能在另一个浏览器正常显示。按理，Meteor会同步这些数据的。

下面的步骤应该可以重现：
1、执行 meteor add insecure，让客户端可以更新服务端的数据（用Todos.allow也是一样）。
2、meteor --release 1.1.0.2 启动服务端，用两个浏览器，分别打开网站
3、在一个浏览器的console里，执行Todos.update(xxx, {$set: {text: "updated"}})，xxx是一个todo的_id
4、在当前浏览器（假设为A）里，网页内容正确更新，但是在另一个浏览器（假设为B）里，这个todo的text取不到，显示为空，只有刷新浏览器之后，才能正常显示。

我简单调试了一下，被更新的这个document，同步到B后，LocalCollection里只有_id，其他数据都没了，而其他没有更新的document则没问题，所有字段都在（也应该在，压根没有更新他们）。服务端用meteor mongo看，所有数据都正常，该更新的都被更新了。客户端（B）里，哪怕用console取Todos.find().fetch()，取出来的对象里，这个document也是只有_id的。

看上去像Meteor数据同步到客户端时的问题，但是纯粹的Meteor应用没问题，甚至我试过不用Meteor的Blaze而用React也没问题。为什么vue会影响meteor的行为？这个问题不搞清楚，没法把vue和meteor结合起来用了，总不能不更新数据啊。

**Comment by yyx990803** [comment]
可是为什么要用 insecure? 用 methods 正常啊

**Comment by yyx990803** [comment]
好吧我知道原因了。Vue 给对象添加了 `$set` 方法，被 `Collection.update` 当成是 mongo modifier 了。这确实比较坑，不过实际使用中我们现在统一推荐用 `Meteor.methods`，不要用 allow/deny.

**Comment by zhongqf** [comment]
原来如此，确实是个大坑。为啥不推荐allow/deny了？真不能用还觉得挺遗憾的，我个人倒是觉得allow/deny做横向的权限check很方便啊，methods用来做纵向的功能。

**Comment by zhongqf** [comment]
@yyx990803 
你用methods正常？我重新试了一下，在`lib/methods.js`里追加
```javascript
   updateTodo: function(id, text) {
      Todos.update(id, {$set: {text: text}})
   }
```
然后再上面的第3步，console里`Meteor.call("updateTodo", "xxx", "updated")`跟原来效果一样啊。insecure已经删掉。

**Comment by yyx990803** [comment]
呃，看来这还真是个问题... 我有空仔细研究下

**Comment by yyx990803** [comment]
现阶段一个简单的 fix: `delete Object.prototype.$set` 就 ok 了。条件就是在 Vue 的代码里，数据对象上无法调用 `$set` （这个本来就不推荐）。vm 上面的 `$set` 还是可以用的。

**Comment by zhongqf** [comment]
@yyx990803 
这个问题解决了么？虽然`delete Object.prototype.$set`能解决问题，但是如果Component里用到了`props`属性，会出`optionsData.$set is not a function`错误。因为在Vue的`instance/scope.js`的`_initData`和`_setData`方法里，用到了`$set`方法。

**Comment by yyx990803** [comment]
1.0 不再添加 prototype 属性了，等正式版吧

**Comment by zhongqf** [comment]
@yyx990803 了解，期待。暂时把$set换了个名字先用着。
