### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vue-webpack-meteor-example#3]
Will this work with the latest version of Meteor? Thanks.

**Comment by yyx990803** [comment]
Yes, this is just a pattern and doesn't rely on any Meteor internals. Theoretically it should work in any Meteor version.

**Comment by niallobrien** [comment]
It might be interesting to use https://atmospherejs.com/webpack/webpack with the latest version of Meteor and update the example to the latest version of Vue.js.
Is there a possibility that MDG might add Vue.js as an official view layer further down the road? Thanks.

**Comment by yyx990803** [comment]
Interesting! I'll definitely take a look at that.

**Comment by ramstein74** [comment]
PLEASE evan :)

2015-11-02 16:39 GMT+00:00 Evan You <notifications@github.com>:

**Comment by niallobrien** [comment]
I have it mostly working here: https://github.com/niallobrien/vue-webpack-meteor-example
Seems that the html is being rendered out to a .js file though. Not sure how to fix.

**Comment by elyase** [comment]
@niallobrien , did you got it to work with webpack:webpack? Do you think hot reload would work this way?

**Comment by niallobrien** [comment]
@elyase unfortunately not.
